name: CI/CD of Personal Portfolio Site
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
              env:
                user_email: ${{secrets.USER_EMAIL}}
                user_name: ${{secrets.USER_NAME}} 
            - name: Setup Identity
              run: git config user.email $env:user_email && git config user.name $env.user_name
            - name: Install Dependencies
              run: npm install
            - name: Run Pre-deploy script
              run: npm run predeploy
            - name: Run Deploy Script
              run: npm run deploy
