name: CI/CD of Personal Portfolio Site
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:  
    deploy:
        permissions:
          pages: write
          id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install Dependencies
              run: npm install
            - name: Run Pre-deploy script
              run: npm run predeploy
            - name: Run Deploy Script
              run: | 
                git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
