name: CI/CD of Personal Portfolio Site
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master 
            - run: npm install
            - run: npm run predeploy
            - run: npm run deploy
            env:
                GITHUB_USER_EMAIL: ${{secrets.USER_EMAIL}}
                GITHUB_USER_NAME: ${{secrets.USER_NAME}}
