name: CI/CD of Personal Portfolio Site
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master 
            - name: Install Dependencies
              run: npm install
            - name: Run Pre-deploy script
              run: npm run predeploy
            - name: Run Deploy Script
              run: npm run deploy
        env:
            GITHUB_USER_EMAIL: ${{secrets.USER_EMAIL}}
            GITHUB_USER_NAME: ${{secrets.USER_NAME}}
